# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FourierEyes
email: jonayboy@gmail.com
force-https: True
description: >
  Yoink
baseurl: "" # the subpath of your site, e.g. /blog
url: "huang-j.github.io" # the base hostname & protocol for your site
twitter_username: RiverOfHuang
github_username: huang-j
name: Jonathan
# Blog
post-preview-words: 96
paginate: 5

# Build settings
highlighter: rouge
markdown: kramdown
permalink: pretty
tracking_id : 'UA-72038855-1'

# list of pages
pages_list:
    About: 'about'
    Projects: 'projects'
    Blog: 'latestpost'
    Contact: 'contact'

gems:
  - jekyll-paginate

paginate_path: "/Blog/page:num/"
